# Build config for Azure Pipelines
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- checkout: self
  lfs: true

- script: npm install
  displayName: 'npm install'
  workingDirectory: 'src'

- script: npm test
  displayName: 'npm test'
  workingDirectory: 'src'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for Reference Implementation'
  condition: succeededOrFailed()
